### ISSUE TITLE
Extension cannot be installed or ran in the browser

### ISSUE THREAD

**Issue by haykam821** [rid9/DateTime#16]

**Comment by rid9** [comment]
Can you please detail exactly what you are trying to do, what you expect to happen, and what happens instead?

**Comment by haykam821** [comment]
When using a version of Visual Studio Code that runs in the browser, such as [vscode.dev](https://vscode.dev/) or [github.dev](https://github.dev/), it is possible to use certain extensions that are considered web-compatible. The [Visual Studio Code documentation](https://code.visualstudio.com/api/extension-guides/web-extensions) defines a web-compatible extension as one that has a `main` entry point but not a `browser` entry point:

> Extensions that have only a `main` entry point, but no `browser` are not web extensions. They are ignored by the web extension host and not available for download in the Extensions view.

Currently, this extension defines a `main` entry point:

https://github.com/rid9/DateTime/blob/ba3c6dbeae09f23f244e69628b951c3240748f21/package.json#L22

Since there is no `browser` entry point, this extension is not considered web-compatible. Therefore, I cannot use the extension from a version of Visual Studio Code that runs in the browser, let alone install it from the Marketplace:

![Information for the 'Date & Time' extension on vscode.dev](https://user-images.githubusercontent.com/24855774/138208534-6d8249b5-bd51-41d8-ae34-1d496c557e9e.png)

However, because the `main` entry point does not seem to use any Node.js-exclusive features, making a separate `browser` entry point with the same path should work just fine.
