### ISSUE TITLE
[Feature Request] Escape the words with square brackets

### ISSUE THREAD

**Issue by gusbemacbe** [rid9/DateTime#19]
Hello, 

Regarding https://momentjs.com/docs/#/displaying/format/, I customised the format:

```json
{
  "dateTime.customFormat": "dddd, D [de] MMMM [de] YYYY [às] HH:mm"
}
```

It produced: `Quarta-feira, 16 d2 Março d2 2022 às 01:38`. The `d2` was wrong, it should be `de`. 

Also see:

- Preview: `[Hoje é] dddd, D [de] MMMM [de] YYYY [às] HH:mm`
- Result: `Hoj2 é Quarta-feira, 16 d2 Março d2 2022 às 01:43`

**Comment by rid9** [comment]
Thank you for the suggestion. Escaping support added in version 2.1.3.

You can see a complete list of supported format options in [the documentation](https://github.com/rid9/DateTime#custom-date--time-format).
