### ISSUE TITLE
Click to copy date/time to clipboard?

### ISSUE THREAD

**Issue by rdhar** [rid9/DateTime#5]
Hi,

First off, great work on such a nifty extension! Frequently, I find myself clicking on it and expecting it to be saved to my clipboard. This would allow the current timestamp to be pasted in a code editor or elsewhere.

Perhaps the format can be set by a separate configuration parameter such as `dateTime.clipboardFormat`. This would allow display of a "human-legible" format while copy/pasting could be in a more standard ISO 8601 format for better code compatibility.

Thanks for your time, really appreciate it.

**Comment by rid9** [comment]
Thank you for the suggestion. This is now implemented in the latest version.

**Comment by rdhar** [comment]
Thank you, I can't believe how quickly you implemented this! Really grateful for your time and effort 🙌

To give something back, I've created PR #6 which adds UTC offset format examples for a more complete [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) output: perfect for `dateTime.clipboardFormat`.

Thanks once again and take care!
